# -*- coding: utf-8 -*-
"""Another copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpUvLSTi8ULuLCke7RY5J5T5eohgFuEx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as mlt
df=pd.read_csv("/content/RELIANCE.NS.csv")

df

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure 'Date' column is in datetime format
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(by='Date').reset_index(drop=True)

# --- Insight 1: Line Chart (Price Trend) ---
print("Chart Name: Price Trend Over Time")
print("Chart Type: Line Chart")
print("Variables Used: X-axis: Date, Y-axis: Close Price")
print("Color Logic: Blue is chosen to signify stability and provide a clear, neutral view of the overall trend in the stock's closing price over the period.")
plt.figure(figsize=(14, 7))
sns.lineplot(x='Date', y='Close', data=df, color='blue')
plt.title('Reliance Industries Limited: Closing Price Trend (2022 onwards)')
plt.xlabel('Date')
plt.ylabel('Closing Price (INR)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
print("Insight / Interpretation: This line chart clearly illustrates the long-term trend of Reliance Industries Limited's closing price. It allows for quick identification of periods of upward or downward movement, indicating the stock's overall performance trajectory and stability over the given timeframe.")
print("\n" * 2) # Add some spacing

# --- Insight 2: Candlestick Chart (Price Movement) ---
print("Chart Name: Daily Price Movement (Candlestick)")
print("Chart Type: Candlestick Chart")
print("Variables Used: X-axis: Date, Y-axis: Open, High, Low, Close")
print("Color Logic: Green indicates a bullish day (Close > Open), while red indicates a bearish day (Close < Open). This directly reflects growth or decline.")

# For candlestick, we need mplfinance, but since it's not imported or available, I will simulate with custom drawing for demonstration
# Or, I can use a simpler representation if mplfinance is not preferred. Let's use matplotlib directly.

# A simple way to plot candlesticks using matplotlib without mplfinance library
def plot_candlestick(df_data, ax):
    for index, row in df_data.iterrows():
        color = 'green' if row['Close'] > row['Open'] else 'red'
        # Plot the wick
        ax.plot([row['Date'], row['Date']], [row['Low'], row['High']], color='black')
        # Plot the body
        ax.plot([row['Date'], row['Date']], [row['Open'], row['Close']], color=color, linewidth=5)

fig, ax = plt.subplots(figsize=(14, 7))
plot_candlestick(df.head(50), ax) # Plotting first 50 days for readability
ax.set_title('Reliance Industries Limited: Daily Price Movement (Candlestick)')
ax.set_xlabel('Date')
ax.set_ylabel('Price (INR)')
ax.grid(True, linestyle='--', alpha=0.6)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
print("Insight / Interpretation: This candlestick chart provides a detailed view of daily price action. Each candle shows the opening, closing, high, and low prices for a given day, indicating market sentiment and volatility. Green candles suggest buying pressure, while red candles indicate selling pressure.")
print("\n" * 2)

# --- Insight 3: Bar Chart (Monthly Average Closing Price) ---
print("Chart Name: Monthly Average Closing Price")
print("Chart Type: Bar Chart")
print("Variables Used: X-axis: Month-Year, Y-axis: Average Closing Price")
print("Color Logic: A 'viridis' gradient is used to differentiate between months, offering a visually appealing progression that highlights variations in average prices across different periods without implying growth/decline for individual bars.")

df['Month_Year'] = df['Date'].dt.to_period('M')
monthly_avg_close = df.groupby('Month_Year')['Close'].mean().reset_index()
monthly_avg_close['Month_Year'] = monthly_avg_close['Month_Year'].astype(str)

plt.figure(figsize=(14, 7))
sns.barplot(x='Month_Year', y='Close', data=monthly_avg_close, palette='viridis', hue='Month_Year', legend=False)
plt.title('Reliance Industries Limited: Monthly Average Closing Price')
plt.xlabel('Month-Year')
plt.ylabel('Average Closing Price (INR)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()
print("Insight / Interpretation: This bar chart illustrates the average closing price of Reliance Industries Limited for each month. It helps identify sustained periods of higher or lower average prices, revealing potential seasonal trends or significant shifts in investor sentiment over medium-term horizons.")
print("\n" * 2)

# --- Insight 4: Histogram (Distribution of Returns) ---
print("Chart Name: Distribution of Daily Returns")
print("Chart Type: Histogram")
print("Variables Used: X-axis: Daily Returns, Y-axis: Frequency")
print("Color Logic: Blue is used to represent stability and clarity in the distribution, allowing for a clear understanding of where the majority of daily returns fall.")

df['Daily_Return'] = df['Close'].pct_change() * 100

plt.figure(figsize=(12, 6))
sns.histplot(df['Daily_Return'].dropna(), bins=50, kde=True, color='blue')
plt.title('Reliance Industries Limited: Distribution of Daily Returns')
plt.xlabel('Daily Return (%)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
print("Insight / Interpretation: The histogram displays the frequency distribution of daily returns, showing how often certain percentage changes occur. A concentrated distribution around zero suggests stable returns, while wider tails indicate higher volatility and the presence of extreme gains or losses.")
print("\n" * 2)

# --- Insight 5: Box Plot (Volatility Analysis) ---
print("Chart Name: Monthly Volatility Analysis (Returns)")
print("Chart Type: Box Plot")
print("Variables Used: X-axis: Month-Year, Y-axis: Daily Returns")
print("Color Logic: Orange/Yellow is chosen to highlight potential high volatility or risk associated with return distributions across different months.")

plt.figure(figsize=(14, 7))
sns.boxplot(x=df['Date'].dt.to_period('M').astype(str), y='Daily_Return', data=df, palette='Oranges')
plt.title('Reliance Industries Limited: Monthly Volatility of Daily Returns')
plt.xlabel('Month-Year')
plt.ylabel('Daily Return (%)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()
print("Insight / Interpretation: This box plot visualizes the spread and skewness of daily returns for each month, indicating monthly volatility. Wider boxes and longer whiskers suggest higher volatility and potential risk, while outliers point to unusual daily price movements.")
print("\n" * 2)

# --- Insight 6: Heatmap (Correlation of Price Components) ---
print("Chart Name: Correlation Heatmap of Price Components")
print("Chart Type: Heatmap")
print("Variables Used: Open, High, Low, Close Prices (Correlation Matrix)")
print("Color Logic: A gradient (Blues) is used to show the intensity of correlation, where darker shades indicate stronger positive correlation and lighter shades indicate weaker correlation.")

correlation_matrix = df[['Open', 'High', 'Low', 'Close']].corr()

plt.figure(figsize=(8, 7))
sns.heatmap(correlation_matrix, annot=True, cmap='Blues', fmt='.2f', linewidths=.5)
plt.title('Reliance Industries Limited: Correlation Matrix of Price Components')
plt.tight_layout()
plt.show()
print("Insight / Interpretation: The heatmap shows the correlation between different price components (Open, High, Low, Close). High positive correlations (close to 1) are expected and confirm that these metrics move in tandem, providing a visual check on the internal consistency of the price data.")
print("\n" * 2)

# --- Insight 7: Scatter Plot (Volume vs Price Change) ---
print("Chart Name: Trading Volume vs. Daily Price Change")
print("Chart Type: Scatter Plot")
print("Variables Used: X-axis: Volume, Y-axis: Daily Price Change (Close - Open)")
print("Color Logic: Blue is chosen for clarity, representing the relationship between two variables without implying growth or decline, focusing on the pattern's stability.")

df['Price_Change'] = df['Close'] - df['Open']

plt.figure(figsize=(12, 7))
sns.scatterplot(x='Volume', y='Price_Change', data=df, color='blue', alpha=0.6)
plt.title('Reliance Industries Limited: Trading Volume vs. Daily Price Change')
plt.xlabel('Volume')
plt.ylabel('Daily Price Change (INR)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
print("Insight / Interpretation: This scatter plot examines the relationship between trading volume and daily price change. It helps in understanding if significant price movements are accompanied by high trading volumes, which can indicate strong conviction behind the price trend or significant market events.")
print("\n" * 2)

# --- Insight 8: Area Chart (Cumulative Returns) ---
print("Chart Name: Cumulative Daily Returns")
print("Chart Type: Area Chart")
print("Variables Used: X-axis: Date, Y-axis: Cumulative Return")
print("Color Logic: A gradient from red to green (RdYlGn) is applied to show the progression of cumulative returns, where green indicates positive growth and red indicates negative performance over time.")

df['Cumulative_Return'] = (1 + df['Daily_Return'] / 100).cumprod() - 1

plt.figure(figsize=(14, 7))
# For area chart, filling between a baseline and the cumulative return
plt.fill_between(df['Date'], 0, df['Cumulative_Return'],
                 where=(df['Cumulative_Return'] >= 0), color='green', alpha=0.5, label='Positive Cumulative Return')
plt.fill_between(df['Date'], 0, df['Cumulative_Return'],
                 where=(df['Cumulative_Return'] < 0), color='red', alpha=0.5, label='Negative Cumulative Return')
sns.lineplot(x='Date', y='Cumulative_Return', data=df, color='black', alpha=0.8, label='Cumulative Return Line') # Overlay a line for clarity

plt.title('Reliance Industries Limited: Cumulative Daily Returns (Normalized to 0 at start)')
plt.xlabel('Date')
plt.ylabel('Cumulative Return')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.tight_layout()
plt.show()
print("Insight / Interpretation: The area chart visualizes the cumulative return of an investment in Reliance Industries Limited, starting from the first date. It clearly shows the overall growth or decline of the portfolio over time, highlighting periods of strong performance or significant drawdowns.")
print("\n" * 2)

# --- Insight 9: Moving Average Overlay Chart (Trend Analysis) ---
print("Chart Name: Price with Moving Averages")
print("Chart Type: Line Chart (with overlays)")
print("Variables Used: X-axis: Date, Y-axis: Close Price, 50-day Moving Average, 200-day Moving Average")
print("Color Logic: Blue for the actual closing price (stability), green for the shorter-term MA (potential growth indicator), and red for the longer-term MA (broader trend/potential resistance or support).")

df['MA_50'] = df['Close'].rolling(window=50).mean()
df['MA_200'] = df['Close'].rolling(window=200).mean()

plt.figure(figsize=(14, 7))
sns.lineplot(x='Date', y='Close', data=df, color='blue', label='Close Price')
sns.lineplot(x='Date', y='MA_50', data=df, color='green', label='50-Day MA')
sns.lineplot(x='Date', y='MA_200', data=df, color='red', label='200-Day MA')
plt.title('Reliance Industries Limited: Closing Price with 50 & 200-Day Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price (INR)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
print("Insight / Interpretation: This chart overlays short-term (50-day) and long-term (200-day) moving averages on the closing price. Crossovers between these lines and the price can indicate changes in trend, offering insights into potential buy/sell signals and overall market sentiment.")
print("\n" * 2)

# --- Insight 10: Volume Chart (Trading Activity) ---
print("Chart Name: Daily Trading Volume")
print("Chart Type: Bar Chart")
print("Variables Used: X-axis: Date, Y-axis: Volume")
print("Color Logic: Blue is chosen to represent general trading activity and consistency over time, providing a clear view of transaction levels.")

plt.figure(figsize=(14, 7))
sns.barplot(x='Date', y='Volume', data=df, color='blue', hue='Date', legend=False)
plt.title('Reliance Industries Limited: Daily Trading Volume')
plt.xlabel('Date')
plt.ylabel('Volume')
# To avoid overcrowded x-axis labels, show only a subset
num_ticks = 10
plt.xticks(np.arange(0, len(df['Date']), len(df['Date'])//num_ticks), df['Date'].dt.strftime('%Y-%m-%d')[::len(df['Date'])//num_ticks], rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
print("Insight / Interpretation: This bar chart displays the daily trading volume, providing insights into the liquidity and investor interest in the stock. Spikes in volume often accompany significant price movements, confirming the strength of a trend or reacting to major news.")
print("\n" * 2)

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# --- Insight 10: Maximum Drawdown Analysis --- (Drawdown Chart)
print("Chart Name: Maximum Drawdown Analysis")
print("Chart Type: Drawdown Chart (using filled area)")
print("Variables Used: X-axis: Date, Y-axis: Drawdown (%)")
print("Color Logic: Red shades to represent drawdowns, darker for deeper ones. Horizontal line at 0% for peak reference.")

# 1. (Already done: Date column converted to datetime and data sorted in previous cells)
# df['Date'] = pd.to_datetime(df['Date'])
# df = df.sort_values(by='Date').reset_index(drop=True)

# 2. Calculate cumulative maximum of Close price
df['Cumulative_Max_Close'] = df['Close'].cummax()

# 3. Compute Drawdown using formula
df['Drawdown_Percentage'] = ((df['Close'] - df['Cumulative_Max_Close']) / df['Cumulative_Max_Close']) * 100

# 4. Plot drawdown over time
plt.figure(figsize=(14, 7))

# Plot the drawdown line itself (optional, can be transparent or light color)
plt.plot(df['Date'], df['Drawdown_Percentage'], color='lightgrey', linestyle='-', linewidth=0.8, alpha=0.7, label='Drawdown Level')

# Use fill_between for shaded region to highlight drawdowns (negative values)
# The 'where' condition ensures only the negative (drawdown) areas are filled.
# Deeper red for deeper drawdowns is implicitly shown by the depth of the red area.
plt.fill_between(df['Date'], df['Drawdown_Percentage'], 0,
                 where=(df['Drawdown_Percentage'] < 0),
                 color='red', alpha=0.6, label='Drawdown Area')

# Add a horizontal line at 0% (peak level reference)
plt.axhline(0, color='black', linestyle='--', linewidth=1, label='Peak Level (0% Drawdown)')

# Labels
plt.title('Reliance Industries - Maximum Drawdown Analysis', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Drawdown (%)', fontsize=12)

# Add grid for readability
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.show()

print("Insight / Interpretation: This drawdown chart visually represents the percentage decline from the stock's historical peak values. It is a critical risk metric, showing how much an investment has fallen from its highest point. Frequent and deep drawdowns (indicated by larger red shaded areas) suggest higher volatility and risk in the stock's behavior, while prolonged periods near the 0% line indicate sustained high performance or recovery.")
print("\n" * 2)